### ISSUE TITLE
Designing of Rating filter is not correct

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-product-filter-for-woocommerce#32]
Bug Name - Designing of Rating filter is not correct
Area Path - Admin dashboard -->MakeWebBetter-->Product Filter for WooCommerce-->Filter Setting-->Add filter
Status - New
Woo Commerce Version - 5.5.2
WordPress Version - 5.8
Plugin Version - 2.0.0
Description - UI of Rating filter is not good at front end.
![ss128](https://user-images.githubusercontent.com/86114080/128176551-80699aef-15c2-46ef-aa75-22b014736566.png)
![ss129](https://user-images.githubusercontent.com/86114080/128176557-d46162ae-6e2e-45da-a17f-b9b999d0e25f.png)

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/128376257-babc9a83-6a87-4fb7-9ac9-95c3b4d7b3c6.png)

now it is looking like rating button

**Comment by shrishti-mwb** [comment]
Done
