### ISSUE TITLE
Designing issue in filter cross-icon

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-product-filter-for-woocommerce#33]
Bug Name - Designing issue in filter cross-icon
Area Path - Go to store-->Apply filter
Status - New
Woo Commerce Version - 5.5.2
WordPress Version - 5.8
Plugin Version - 2.0.0
Description - Design of filter cross-icon is not correct
![ss132](https://user-images.githubusercontent.com/86114080/128177525-001819ac-860d-4875-a329-f99191a5b176.png)

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/128382586-c668fe87-ed2f-478d-bb84-ad9cd36ca8bd.png)
fixed issue

**Comment by shrishti-mwb** [comment]
Done
