### ISSUE TITLE
Filter-cross icon is stick with reset filter button

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-product-filter-for-woocommerce#36]
Bug Name - Filter-cross icon is stick with reset filter button
Area Path - Go to store-->Apply filters
Woo Commerce Version - 5.5.2
WordPress Version - 5.8
Plugin Version - 2.0.0
Description - Filter-cross icon is stick with reset filter button, it should be below of filters.
![ss133](https://user-images.githubusercontent.com/86114080/128189601-d2ca6a85-9c9b-4ed7-a235-54d952b78bf4.png)

**Comment by Sukirti-CEDCOSS** [comment]
Verified
