### ISSUE TITLE
There is no on-boarding pop-up when we activate plugin

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-product-filter-for-woocommerce#47]
Bug Name - There is no on-boarding pop-up when we activate plugin
Area Path - Enable plugin
Woo Commerce Version - 5.6.0
WordPress Version - 5.8
Plugin Version - 2.0.0
Description - There is no on-boarding pop-up when we activate plugin

**Comment by ahmadabbas-cedcoss** [comment]
please make a new site and check if the problem persist or not
because popup is coming on my site

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by Sukirti-CEDCOSS** [comment]
The submission is not received at other side

**Comment by ahmadabbas-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
