### ISSUE TITLE
Deactivation form is not working when we input details

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-product-filter-for-woocommerce#48]
Bug Name - Deactivation form is not working when we input details
Area Path - Enable plugin-->deactivate plugin
Woo Commerce Version - 5.6.0
WordPress Version - 5.8
Plugin Version - 2.0.0
Description - Deactivation form is not working when we input details.

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by Sukirti-CEDCOSS** [comment]
The submission is not received on another side

**Comment by ahmadabbas-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
