### ISSUE TITLE
Issue with plugin's version name

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#50]
Woo Commerce Version - 5.5.2
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: The plugin is version 2.0.0 but the mentioned version is 1.0.0

![image](https://user-images.githubusercontent.com/85384857/134545523-beb20c24-d6d4-4412-abac-9747a38098da.png)

**Comment by ahmadabbas-cedcoss** [comment]
1.0.1 plugin name updated

**Comment by Sukirti-CEDCOSS** [comment]
Verified
