### ISSUE TITLE
The filter marked as undefined under the specific setting

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#51]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: The filter marked as undefined under the specific setting 
![image](https://user-images.githubusercontent.com/85384857/134681413-392cc490-2317-4d7e-a83a-0bd72086e6aa.png)
![image](https://user-images.githubusercontent.com/85384857/134681438-51d13c12-046d-4606-83c6-f7f7d4910c1d.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
