### ISSUE TITLE
Issue with the AND and OR logic

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#52]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: The Login AND and OR should apply properly.

![image](https://user-images.githubusercontent.com/85384857/134685280-71a3b981-7018-4b25-a555-ba3cddb3b17d.png)
![image](https://user-images.githubusercontent.com/85384857/134685303-250da5f7-9009-428a-93f2-0b82d70f4176.png)

**Comment by ahmadabbas-cedcoss** [comment]
does attributes present in the products respectively?

**Comment by Sukirti-CEDCOSS** [comment]
Verified
