### ISSUE TITLE
Issue when selecting Attribute-size and filter type-slider

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#53]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: If the particular setting is not applicable it should give a warning but not save.

![image](https://user-images.githubusercontent.com/85384857/134690829-1acf1bf5-2e98-4bc2-8506-0943204f58e0.png)
![image](https://user-images.githubusercontent.com/85384857/134690845-d4aba262-d8b2-40fd-87d1-f404d6f285aa.png)

**Comment by ahmadabbas-cedcoss** [comment]
slider is only for price

**Comment by Sukirti-CEDCOSS** [comment]
Verified
