### ISSUE TITLE
checkbox option under filter type is showing undefined filter 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#54]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: checkbox option under filter type is showing undefined filter 

![image](https://user-images.githubusercontent.com/85384857/134692308-23f7002f-ca27-4268-9fa9-a98182f36c6f.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
