### ISSUE TITLE
If we are terminating filter by cancelling cross icon then the check box should go back to its original position  

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#56]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: If we are terminating the filter by canceling the cross icon then the check box should go back to its original position  

![image](https://user-images.githubusercontent.com/85384857/134694522-ff61269b-a893-4db3-b4ff-3aa7817aad1d.png)
![image](https://user-images.githubusercontent.com/85384857/134694651-bdf06d33-f2ec-4852-b60d-3887fe9409aa.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
