### ISSUE TITLE
The setting "Show them separate with cross icon" seems not to be working when selecting "Filter for - Attribute"

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#57]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: The setting "Show them separate with cross icon" seems not to be working when selecting "Filter for - Attribute".
![image](https://user-images.githubusercontent.com/85384857/134757594-4a0016ab-3256-4257-81b9-0c69acbe11bd.png)
![image](https://user-images.githubusercontent.com/85384857/134757599-0e8051dd-e917-410c-bbbf-1b97680c4668.png)
![image](https://user-images.githubusercontent.com/85384857/134757605-333ff9d0-e778-47c5-b5ba-ad5e1ffeafe8.png)

**Comment by ahmadabbas-cedcoss** [comment]
works only with non custom attributes

**Comment by Sukirti-CEDCOSS** [comment]
Verified
