### ISSUE TITLE
In custom selected attribute the first option is not working properly is if the type of filter is dropdown

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#58]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: In custom selected attribute the first option is not working properly
![image](https://user-images.githubusercontent.com/85384857/134757889-330a9642-7632-4e35-97b9-81691a336644.png)
![image](https://user-images.githubusercontent.com/85384857/134757949-26fcc404-f9a2-4dce-8b26-9a11d281d27d.png)

**Comment by ahmadabbas-cedcoss** [comment]
sorry this is only compatible with input type text

**Comment by Sukirti-CEDCOSS** [comment]
Reason commented, fine for now
