### ISSUE TITLE
After selecting filter. when clicked "show only instock item" all items were appeared

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#59]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: After selecting a filter. when clicked "show only in-stock item" all items have appeared
![image](https://user-images.githubusercontent.com/85384857/134758436-c11cbe39-da83-4c95-8495-ed9ba43bb0a1.png)
![image](https://user-images.githubusercontent.com/85384857/134758438-4413cf7c-cbd9-41c9-af21-81e2014ccaca.png)
![image](https://user-images.githubusercontent.com/85384857/134758444-f3f1f2e0-b1c0-4ff6-9e2f-7eb2f68297e3.png)

**Comment by ahmadabbas-cedcoss** [comment]
show in stock is a separate filter it will work separately

**Comment by Sukirti-CEDCOSS** [comment]
Reason commented, fine for now
