### ISSUE TITLE
When selected rating filter, the Icon should change it's colour to indicate that it's selected

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#61]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: When selected rating filter, the icon should change its color to indicate that it's selected
![image](https://user-images.githubusercontent.com/85384857/134760782-d9f93dfd-2281-4e75-9ae3-fe856f28d23c.png)
![image](https://user-images.githubusercontent.com/85384857/134760783-9c12c2f2-293c-4fb7-9fac-5860bb13004b.png)

**Comment by ahmadabbas-cedcoss** [comment]
sorry this feature is not present in this version

**Comment by Sukirti-CEDCOSS** [comment]
Reason commented, fine for now
