### ISSUE TITLE
By unchecking the check box, the products go back to normal but the selected filter inbox does not go back

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-product-filter-for-woocommerce#63]
Woo Commerce Version - 5.7
WordPress Version - 5.8
Plugin Version - 2.0.0
Description: By unchecking the check box, the products go back to normal but the selected filter inbox does not go back

![image](https://user-images.githubusercontent.com/85384857/135848700-bbf1b787-7a3e-4381-baf6-649349cbb73a.png)
![image](https://user-images.githubusercontent.com/85384857/135848713-a7366bde-3fab-47f1-bab4-d88b4bb8ce97.png)

**Comment by ahmadabbas-cedcoss** [comment]
not possible with the checkbox type filter

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
